### ISSUE TITLE
Use enumerator in ExecCmd? 

### ISSUE THREAD

**Issue by AnantTiwari-Naman** [mell-o-tron/MellOs#1]
As more commands get added to CmdMode, just comparing numbers will get pretty unmanageable. Maybe make an enumerator Commands for those commands?

**Comment by KingUndeadCodes** [comment]
You can add it yourself if you want to.

If you want to talk about you can join the discord:
https://discord.gg/taJ5hUcM

**Comment by mell-o-tron** [comment]
I'll probably remove the whole "command mode" in the next update, I'll make a more complex shell as soon as I'll implement a file system.

**Comment by KingUndeadCodes** [comment]
> I'll probably remove the whole "command mode" in the next update, I'll make a more complex shell as soon as I'll implement a file system.

Nice. When will that be?
