### ISSUE TITLE
Ubuntu 22.04 WSL having issues with "tar xf binutils-2.35.1.tar.gz"

### ISSUE THREAD

**Issue by Lilafian** [mell-o-tron/MellOs#17]
Ubuntu 22.04 WSL displays this issue with command "**tar xf binutils-2.35.1.tar.gz**":
![weird](https://user-images.githubusercontent.com/102885633/177862594-64ab3125-f52f-47bd-8f40-497e89ec7c27.png)

**Comment by Lilafian** [comment]
Still getting an error after running shell script.
![image](https://user-images.githubusercontent.com/102885633/177915024-e223a1f6-9132-4bff-9bab-488aaca67182.png)

**Comment by mell-o-tron** [comment]
Uhm yeah that's the very same error... I've never seen it. 

Could you try the same command on another machine, to check whether it depends on your machine?

**Comment by Hubber101** [comment]
Same exact error for me... help

**Comment by mell-o-tron** [comment]
I've found this stackexchange question about a very similar error:

https://askubuntu.com/q/1417255
