### ISSUE TITLE
Makefile fix?

### ISSUE THREAD

**Issue by taitep** [mell-o-tron/MellOs#44]
I would like to try out MellOS, but i could not figure out ho to run it, as i managed to just use pacman (i use manjaro btw) to install the programs mentioned, and the files are not in the correct places. I usggest expecting people to add the locations to path and use that in the makefile.

**Comment by somecollagist** [comment]
The setup scripts should manage everything for you down to absolute paths to the cross compiler - are you sure that setup-arch.sh ran correctly on your machine? Could you also send the output from the shell so we can have a look at exactly what's gone wrong? Cheers :)

**Comment by taitep** [comment]
i did not run it, did not think and just intalled standard gcc and ld.
