### ISSUE TITLE
Help command does not print all the commands(?)

### ISSUE THREAD

**Issue by mell-o-tron** [mell-o-tron/MellOs#46]
The help command prints a bunch of colons from some point on, and the commands that are not printed do not work. There must be something wrong in the shell code but I can't seem to figure out what.

![Screenshot_20231230_230108](https://github.com/mell-o-tron/MellOs/assets/76403900/5d82b4ba-b2c1-4b44-96dc-9616ff714e43)

**Comment by truemaker** [comment]
I made a pull request solving this problem
